language: python

python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

# command to install dependencies
install:
  - "pip install pyserial"
  - "pip install scripttest"

# command to run tests
script: nosetests -v ./tests/test_cc2538-bsl.py
