language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

# command to install dependencies
install:
  - "pip install pyserial"
  - "pip install scripttest"
  - "pip install flake8"

# command to run tests
script:
  - python3 -m flake8 cc2538-bsl.py
  - nosetests -v ./tests/test_cc2538-bsl.py
